name: Continuous deployment

on:
  push:
    branches:
      - master
  release:

jobs:
  build-macos:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7      
    - name: Install packaging dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip install -r package/requirements.txt
    - name: Run PyInstaller
      run: |
        cd package
        pyinstaller --noconfirm crispy.spec
        cd ..
    - name: Upload the .dmg file
      uses: actions/upload-artifact@v2
      with:
        name: Crispy-macOS-10.15
        path : package/artifacts/Crispy.dmg